Package                              | Source                 | Why                                       | Maintainer                                                     | Deb Size (B)    | Inst Size (KB) 
-------------------------------------+------------------------+-------------------------------------------+----------------------------------------------------------------+-----------------+-----------------
adduser                              | adduser                | apt                                       | Ubuntu Core Developers <ubuntu-devel-discuss@lists.ubuntu.com> |          162792 |             624
amd64-microcode                      | amd64-microcode        | linux-image-generic                       | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           31752 |              76
apt                                  | apt                    | apt-utils                                 | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |         1288960 |            4182
apt-utils                            | apt                    | debconf (Recommends)                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          213336 |             832
busybox-initramfs                    | busybox                | initramfs-tools-core                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          168636 |             367
ca-certificates                      | ca-certificates        | apt (Recommends)                          | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          146336 |             384
coreutils                            | coreutils              | ucf                                       | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |         1249368 |            7196
cpio                                 | cpio                   | initramfs-tools-core                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           86044 |             368
crda                                 | crda                   | linux-modules-extra-5.4.0-26-generic      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           63476 |             265
dbus                                 | dbus                   | libdbus-1-3 (Recommends)                  | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          151088 |             618
debconf                              | debconf                | grub-pc                                   | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          121524 |             520
debconf-i18n                         | debconf                | debconf (Recommends)                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          206284 |             781
dmsetup                              | lvm2                   | libdevmapper1.02.1 (Recommends)           | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           75576 |             270
dpkg                                 | dpkg                   | perl-base                                 | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |         1127856 |            6740
gcc-10-base                          | gcc-10                 | libgcc-s1                                 | Ubuntu Core developers <ubuntu-devel-discuss@lists.ubuntu.com> |           19024 |             256
gettext-base                         | gettext                | grub-common                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           50244 |             364
gpgv                                 | gnupg2                 | apt                                       | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          199804 |             499
grub-common                          | grub2                  | grub-pc                                   | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |         1852632 |           13272
grub-gfxpayload-lists                | grub-gfxpayload-lists  | grub-pc                                   | Colin Watson <cjwatson@ubuntu.com>                             |            3658 |              47
grub-pc                              | grub2                  | Ubuntu.Bionic boot seed                   | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          124692 |             554
grub-pc-bin                          | grub2                  | grub-pc                                   | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          969136 |            3102
grub2-common                         | grub2                  | grub-pc                                   | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          589024 |            1310
initramfs-tools                      | initramfs-tools        | linux-image-5.4.0-26-generic (Recommends) | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |            9212 |             143
initramfs-tools-bin                  | initramfs-tools        | initramfs-tools-core                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           14280 |             131
initramfs-tools-core                 | initramfs-tools        | initramfs-tools                           | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           47448 |             271
intel-microcode                      | intel-microcode        | linux-image-generic                       | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |         2407684 |            2962
iucode-tool                          | iucode-tool            | intel-microcode                           | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           45600 |              98
iw                                   | iw                     | crda                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           93968 |             283
klibc-utils                          | klibc                  | initramfs-tools-core                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           95024 |             542
kmod                                 | kmod                   | linux-image-5.4.0-26-generic              | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           93904 |             255
libacl1                              | acl                    | tar                                       | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           18820 |              70
libapparmor1                         | apparmor               | dbus                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           34252 |             167
libapt-pkg6.0                        | apt                    | apt                                       | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          833812 |            3300
libattr1                             | attr                   | coreutils                                 | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           12748 |              57
libaudit-common                      | audit                  | libaudit1                                 | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |            3936 |              24
libaudit1                            | audit                  | passwd                                    | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           38856 |             157
libblkid1                            | util-linux             | udev                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          136716 |             439
libbz2-1.0                           | bzip2                  | dpkg                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           32308 |              99
libc6                                | glibc                  | perl-base                                 | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |         2713080 |           13245
libcap-ng0                           | libcap-ng              | libaudit1                                 | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           11080 |              45
libcrypt1                            | libxcrypt              | libc6                                     | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           78204 |             226
libdb5.3                             | db5.3                  | libpam-modules                            | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          675076 |            1749
libdbus-1-3                          | dbus                   | thermald                                  | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          179168 |             465
libdbus-glib-1-2                     | dbus-glib              | thermald                                  | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           59100 |             212
libdevmapper1.02.1                   | lvm2                   | grub-common                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          127216 |             484
libefiboot1                          | efivar                 | grub-common                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           38120 |             117
libefivar1                           | efivar                 | libefiboot1                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           47756 |             170
libelf1                              | elfutils               | linux-headers-5.4.0-26-generic            | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           44004 |             184
libexpat1                            | expat                  | dbus                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           73292 |             401
libffi7                              | libffi                 | libp11-kit0                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           19688 |              65
libfreetype6                         | freetype               | grub-common                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          340708 |             836
libfuse2                             | fuse                   | grub-common                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           81972 |             313
libgcc-s1                            | gcc-10                 | libc6                                     | Ubuntu Core developers <ubuntu-devel-discuss@lists.ubuntu.com> |           41576 |             120
libgcrypt20                          | libgcrypt20            | gpgv                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          419496 |            1224
libglib2.0-0                         | glib2.0                | libdbus-glib-1-2                          | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |         1284284 |            3988
libglib2.0-data                      | glib2.0                | libglib2.0-0 (Recommends)                 | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |            6436 |             104
libgmp10                             | gmp                    | libgnutls30                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          240448 |             567
libgnutls30                          | gnutls28               | apt                                       | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          828448 |            2192
libgpg-error-l10n                    | libgpg-error           | libgpg-error0 (Recommends)                | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |            6880 |              60
libgpg-error0                        | libgpg-error           | libgcrypt20                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           58004 |             176
libhogweed5                          | nettle                 | libgnutls30                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          137896 |             241
libicu66                             | icu                    | libxml2                                   | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |         8520140 |           32773
libidn2-0                            | libidn2                | libc6 (Recommends)                        | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           50448 |             216
libklibc                             | klibc                  | klibc-utils                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           42860 |             113
libkmod2                             | kmod                   | kmod                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           44328 |             134
liblocale-gettext-perl               | liblocale-gettext-perl | debconf-i18n                              | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           17064 |              54
liblz4-1                             | lz4                    | libapt-pkg6.0                             | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           55928 |             149
liblzma5                             | xz-utils               | dpkg                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           92352 |             259
libmount1                            | util-linux             | util-linux                                | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          148832 |             481
libnettle7                           | nettle                 | libhogweed5                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          114416 |             395
libnl-3-200                          | libnl3                 | crda                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           53864 |             180
libnl-genl-3-200                     | libnl3                 | crda                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           11140 |              57
libp11-kit0                          | p11-kit                | libgnutls30                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          188260 |            1270
libpam-modules                       | pam                    | passwd                                    | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          250036 |            1135
libpam-modules-bin                   | pam                    | libpam-modules                            | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           37676 |             322
libpam-runtime                       | pam                    | login                                     | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           37268 |             304
libpam0g                             | pam                    | passwd                                    | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           55444 |             231
libpcre2-8-0                         | pcre2                  | libselinux1                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          197268 |             592
libpcre3                             | pcre3                  | libglib2.0-0                              | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          232028 |             671
libpng16-16                          | libpng1.6              | libfreetype6                              | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          179076 |             341
libseccomp2                          | libseccomp             | apt                                       | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           41556 |             348
libselinux1                          | libselinux             | dpkg                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           68784 |             202
libsemanage-common                   | libsemanage            | libsemanage1                              | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |            9792 |              36
libsemanage1                         | libsemanage            | passwd                                    | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           85528 |             305
libsepol1                            | libsepol               | libsemanage1                              | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          252020 |             738
libsmartcols1                        | util-linux             | util-linux                                | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          100280 |             337
libssl1.1                            | openssl                | openssl                                   | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |         1318204 |            4026
libstdc++6                           | gcc-10                 | libapt-pkg6.0                             | Ubuntu Core developers <ubuntu-devel-discuss@lists.ubuntu.com> |          503412 |            2432
libsystemd0                          | systemd                | libapt-pkg6.0                             | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          270584 |             860
libtasn1-6                           | libtasn1-6             | libgnutls30                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           38088 |             125
libtext-charwidth-perl               | libtext-charwidth-perl | libtext-wrapi18n-perl                     | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |            9872 |              41
libtext-iconv-perl                   | libtext-iconv-perl     | debconf-i18n                              | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           13792 |              48
libtext-wrapi18n-perl                | libtext-wrapi18n-perl  | debconf-i18n                              | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |            8264 |              25
libtinfo6                            | ncurses                | util-linux                                | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           86980 |             537
libudev1                             | systemd                | libapt-pkg6.0                             | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           78348 |             326
libunistring2                        | libunistring           | libidn2-0                                 | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          368092 |            1582
libuuid1                             | util-linux             | util-linux                                | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           20092 |             122
libxml2                              | libxml2                | shared-mime-info                          | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          639872 |            1923
libzstd1                             | libzstd                | dpkg                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          236880 |             700
linux-base                           | linux-base             | linux-image-5.4.0-26-generic              | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           17664 |              57
linux-firmware                       | linux-firmware         | linux-image-generic                       | Ubuntu Kernel Team <kernel-team@lists.ubuntu.com>              |        98718284 |          522910
linux-generic                        | linux-meta             | Ubuntu.Bionic boot seed                   | Ubuntu Kernel Team <kernel-team@lists.ubuntu.com>              |            1900 |              17
linux-generic-hwe-18.04              | linux-meta             | Ubuntu.Bionic boot seed                   | Ubuntu Kernel Team <kernel-team@lists.ubuntu.com>              |            1888 |              17
linux-headers-5.4.0-26               | linux                  | linux-headers-5.4.0-26-generic            | Ubuntu Kernel Team <kernel-team@lists.ubuntu.com>              |        10944024 |           69041
linux-headers-5.4.0-26-generic       | linux                  | linux-headers-generic                     | Ubuntu Kernel Team <kernel-team@lists.ubuntu.com>              |         1221404 |           13975
linux-headers-generic                | linux-meta             | linux-generic                             | Ubuntu Kernel Team <kernel-team@lists.ubuntu.com>              |            2680 |              17
linux-image-5.4.0-26-generic         | linux-signed           | linux-image-generic                       | Canonical Kernel Team <kernel-team@lists.ubuntu.com>           |         8875784 |           11415
linux-image-generic                  | linux-meta             | Ubuntu.Bionic boot seed                   | Ubuntu Kernel Team <kernel-team@lists.ubuntu.com>              |            2796 |              17
linux-image-generic-hwe-18.04        | linux-meta             | Ubuntu.Bionic boot seed                   | Ubuntu Kernel Team <kernel-team@lists.ubuntu.com>              |            1884 |              17
linux-modules-5.4.0-26-generic       | linux                  | linux-image-5.4.0-26-generic              | Ubuntu Kernel Team <kernel-team@lists.ubuntu.com>              |        14285092 |           70717
linux-modules-extra-5.4.0-26-generic | linux                  | linux-image-generic                       | Ubuntu Kernel Team <kernel-team@lists.ubuntu.com>              |        38614000 |          185508
login                                | shadow                 | util-linux                                | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          221228 |             932
logsave                              | e2fsprogs              | initramfs-tools-core                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           10180 |              92
lsb-base                             | lsb                    | grub-common                               | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           12076 |              58
lz4                                  | lz4                    | initramfs-tools-core                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           82656 |             222
mawk                                 | mawk                   | Ubuntu.Bionic boot seed                   | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           95992 |             233
openssl                              | openssl                | ca-certificates                           | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          620552 |            1257
os-prober                            | os-prober              | grub-common (Recommends)                  | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           20076 |             111
passwd                               | shadow                 | adduser                                   | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          797964 |            2667
perl-base                            | perl                   | debconf                                   | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |         1511376 |           10779
sensible-utils                       | sensible-utils         | ucf                                       | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           15016 |              62
shared-mime-info                     | shared-mime-info       | libglib2.0-0 (Recommends)                 | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          430464 |            2652
tar                                  | tar                    | dpkg                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          240016 |             880
thermald                             | thermald               | linux-image-generic (Recommends)          | Colin King <colin.king@canonical.com>                          |          196948 |             606
tzdata                               | tzdata                 | libicu66                                  | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |          293692 |            3928
ubuntu-keyring                       | ubuntu-keyring         | apt                                       | Dimitri John Ledkov <dimitri.ledkov@canonical.com>             |           22244 |              46
ucf                                  | ucf                    | grub-pc                                   | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           51620 |             188
udev                                 | systemd                | initramfs-tools-core                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |         1361960 |            9111
update-motd                          | update-motd            | libpam-modules (Recommends)               | Dustin Kirkland <kirkland@ubuntu.com>                          |            5224 |              21
util-linux                           | util-linux             | udev                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |         1020452 |            4538
uuid-runtime                         | util-linux             | libuuid1 (Recommends)                     | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           35292 |             212
wireless-regdb                       | wireless-regdb         | crda                                      | Seth Forshee <seth.forshee@canonical.com>                      |           11040 |              33
xdg-user-dirs                        | xdg-user-dirs          | libglib2.0-0 (Recommends)                 | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           48284 |             541
zlib1g                               | zlib                   | dpkg                                      | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>      |           53700 |             163
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+-----------------
                                                                                                                                                                           |       214656062 |         1046239
